[package]
name = "vfio-ioctls"
version = "0.0.1"
authors = ["The Cloud Hypervisor Authors"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

[dependencies]
vm-memory = { git = "https://github.com/rust-vmm/vm-memory", features = ["backend-mmap"] }
